- name: variablees from titles
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter username
    private: false
  - name: PASSWORD
    prompt: Enter password
    private: True 
  tasks:
  - name: print overide info
    ansible.builtin.debug:
      msg: "hi there, how are you? my name is {{USERNAME}} and i am learning {{PASSWORD}}"